version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx:1.21.3
    volumes:
      - './nginx:/etc/nginx/conf.d/'
      - './src:/var/www/html'
    ports:
      - "80:80"
    depends_on:
      - mysql
      - php-fpm
  php-fpm:
    build: php-fpm
    container_name: php-fpm
    restart: always
    volumes:
      - './src:/var/www/html'
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
        - MYSQL_DATABASE=watchlist
        - MYSQL_ROOT_PASSWORD=root123
    #ports:
        #- "3307:3306"
    volumes:
        - './mysql:/var/lib/mysql'
  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
        - "9000:80"
    environment:
        - PMA_ARBITRARY=0
        - PMA_HOST=mysql